### ISSUE TITLE
Old version of Microsoft.Build.Tasks.Git cannot read git repo (GitHub)

### ISSUE THREAD

**Issue by chklauser** [dotnet/reproducible-builds#39]
Our project references `DotNet.ReproducibleBuild` in version `1.1.1`. This package pulls in a rather old version of `Microsoft.Build.Tasks.Git` (1.1.1). With this version, our build fails on GitHub in combination with the default options of the `actions/checkout@v4` action 

Our GH actions pipeline
```yaml
on:
  release:
    types:
    - published

# ...

jobs:
  release:
    steps:
    - uses: actions/checkout@v4
```

The error message
```
/root/.nuget/packages/microsoft.build.tasks.git/1.1.1/build/Microsoft.Build.Tasks.Git.targets(25,5): error : Error reading git repository information: Unsupported repository version 1. Only versions up to 0 are supported.
```

# Workaround
Explicitly reference a more recent version of `Microsoft.Build.Tasks.Git`
```xml
<PackageVersion Include="Microsoft.Build.Tasks.Git" Version="8.0.0" PrivateAssets="All" />
```
